name: Build (all platforms, all targets, all haxe versions)

on: [push, repository_dispatch]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        #haxe-version: [3.4.4, 4.0.3]
        os: [ubuntu-latest]
        haxe-version: [3.4.4]

    steps:
    - uses: actions/checkout@v1
    - uses: haxeui/haxeui-core/.github/actions/haxe@master
      with:
        haxe-version: ${{ matrix.haxe-version }}

    - name: Build app (haxe ${{ matrix.haxe-version }}, ${{ matrix.os }})
      run: |
        git clone --branch master https://github.com/haxeui/haxeui-core.git --depth=1
        haxelib dev haxeui-core haxeui-core
        haxelib install hxcpp --always
        haxelib install openfl
        echo "y" | haxelib run openfl setup
